from test_uncollected import TestUncollected
from test_noncompliance import TestNonCompliance
from test_compliance import TestCompliance
from test_exception import TestException
from test_totals import TestTotals
from test_collected import TestCollected
